import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const homeStory = readFileSync("src/components/home/homeScreenStory.ts", "utf8");
const mobileStory = homeStory.match(/const drawMobileStory =[\s\S]*?const drawDesktopStoryLegacy/)?.[0] ?? "";
const mobileRule = mobileStory.match(/const drawMobileRule =[\s\S]*?const introHeroX/)?.[0] ?? "";
const mobileIntroRule = mobileStory.match(/const drawMobileIntroRule =[\s\S]*?const drawMobileIntroFlow/)?.[0] ?? "";
const mobileIntroFlow = mobileStory.match(/const drawMobileIntroFlow =[\s\S]*?const drawMobileIntroMaterial/)?.[0] ?? "";
const mobileIntroMaterial = mobileStory.match(/const drawMobileIntroMaterial =[\s\S]*?type MobileInputCard/)?.[0] ?? "";
const mobileChapterTitle = mobileStory.match(/const drawMobileChapterTitle =[\s\S]*?const drawMobileIntroRule/)?.[0] ?? "";
const mobileEditorialInput = mobileStory.match(/const drawMobileEditorialInput =[\s\S]*?const drawMobileClassifyTrack/)?.[0] ?? "";
const mobileClassifyTrack = mobileStory.match(/const drawMobileClassifyTrack =[\s\S]*?const drawMobileEditorialWork/)?.[0] ?? "";
const mobileClassifyMorphGroup = mobileStory.match(/const drawMobileClassifyMorphGroup =[\s\S]*?const drawMobileEditorialWork/)?.[0] ?? "";
const mobileEditorialWork = mobileStory.match(/const drawMobileEditorialWork =[\s\S]*?const drawMobileClassifyToWorkMorph/)?.[0] ?? "";
const mobileClassifyWorkMorph = mobileStory.match(/const drawMobileClassifyToWorkMorph =[\s\S]*?const drawMobileEditorialSnapshot/)?.[0] ?? "";
const mobileBuildIndexRow = mobileStory.match(/const drawMobileBuildIndexRow =[\s\S]*?const drawMobileTodayBuildHeading/)?.[0] ?? "";
const mobileTodayPanel = mobileStory.match(/const drawMobileTodayPanel =[\s\S]*?const introToInput/)?.[0] ?? "";
const mobileInputClassifyScene = mobileStory.match(/const introToInput = phase\(progress, 0\.12, 0\.38\);[\s\S]*?if \(buildBridge > 0\.001\)/)?.[0] ?? "";

test("mobile intro reads as a centered cover field instead of a large route diagram", () => {
  assert.ok(mobileStory.includes("const introHeroY = height * 0.49;"));
  assert.ok(mobileStory.includes("const introHeroX = width * 0.5;"));
  assert.ok(mobileStory.includes("const introHeroW = Math.min(width * 0.48, 210 * unit);"));
  assert.ok(mobileStory.includes("const introHeroH = 142 * unit;"));
  assert.ok(mobileStory.includes("const mobileInputNumberW = 34 * unit;"));
  assert.ok(mobileStory.includes("const mobileInputTitleMinSize = 9.2 * unit;"));
  assert.ok(mobileStory.includes("const mobileInputBodyWidth = cardW - 20 * unit;"));
  assert.ok(mobileStory.includes("const introFlowMotion = input.motion ?? progress;"));
  assert.ok(mobileStory.includes("const introSingleW = Math.min(safe.w * 0.48, introHeroW * 0.9);"));
  assert.ok(mobileStory.includes("const introTopPairY = introHeroY - introHeroH * 1.45;"));
  assert.ok(mobileStory.includes("const introTopSingleY = introHeroY - introHeroH * 0.9;"));
  assert.ok(mobileStory.includes("const introBottomSingleY = introHeroY + introHeroH * 0.74;"));
  assert.ok(mobileStory.includes("const introBottomPairY = introHeroY + introHeroH * 1.32;"));
  assert.ok(mobileStory.includes("const introLabelRects = ["));
  assert.ok(mobileStory.includes("x: introHeroX - introSingleW / 2, y: introTopSingleY"));
  assert.ok(mobileStory.includes("x: introHeroX - introSingleW / 2, y: introBottomSingleY"));
  assert.ok(mobileStory.includes("const mobileIntroSlots = introLabelRects.map((rect) => ({ ...rect }));"));
  assert.ok(mobileStory.includes("const drawMobileIntroRule = (rect: Rect, item: (typeof STORY_MATERIALS)[number], amount: number) => {"));
  assert.ok(mobileStory.includes("const introRuleColor = item.active ? palette.aiAccent : palette.muted;"));
  assert.ok(mobileStory.includes("const introRuleW = 60 * unit;"));
  assert.ok(mobileStory.includes("const introRuleDotGap = 10 * unit;"));
  assert.ok(mobileIntroRule.includes("ctx.lineWidth = 1.35 * unit;"));
  assert.ok(mobileStory.includes("ctx.arc(rect.x + introRuleW + introRuleDotGap, rect.y + 2 * unit, 3.2 * unit, 0, Math.PI * 2);"));
  assert.ok(mobileStory.includes("const drawMobileIntroFlow = (rect: Rect, item: (typeof STORY_MATERIALS)[number], toward: 1 | -1, amount: number, index: number) => {"));
  assert.ok(mobileStory.includes("const introFlowGap = 10 * unit;"));
  assert.ok(mobileStory.includes("const introLabelTopY = rect.y + 2 * unit;"));
  assert.ok(mobileStory.includes("const introLabelBottomY = rect.y + 39 * unit;"));
  assert.ok(mobileStory.includes("const startY = toward === 1 ? introLabelBottomY + introFlowGap : introLabelTopY - introFlowGap;"));
  assert.ok(mobileStory.includes("const targetY = toward === 1 ? introHeroY - introHeroH * 0.2 : introHeroY + introHeroH * 0.24;"));
  assert.ok(mobileStory.includes("const targetX = introHeroX + (startX - introHeroX) * 0.16;"));
  assert.ok(mobileStory.includes("const isCenterIntroFlow = index === 2 || index === 3;"));
  assert.ok(mobileStory.includes("const side = Math.abs(startX - introHeroX) < 6 * unit ? index === 2 ? -1 : 1 : startX < introHeroX ? -1 : 1;"));
  assert.ok(mobileStory.includes("const introFlowBend = side * (isCenterIntroFlow ? 18 * unit : 30 * unit);"));
  assert.ok(mobileStory.includes("const firstControlX = startX + introFlowBend;"));
  assert.ok(mobileStory.includes("const secondControlX = targetX + introFlowBend * 0.45;"));
  assert.ok(mobileStory.includes("ctx.bezierCurveTo(firstControlX, startY + travelY * 0.28, secondControlX, startY + travelY * 0.74, targetX, targetY);"));
  assert.ok(mobileStory.includes("const flowColor = item.active ? palette.aiAccent : palette.muted;"));
  assert.ok(mobileStory.includes("withAlpha(ctx, amount * (item.active ? 0.8 : 0.38), () => {"));
  assert.ok(mobileIntroFlow.includes("ctx.globalAlpha *= item.active ? 0.5 : 0.34;"));
  assert.ok(mobileIntroFlow.includes("ctx.setLineDash([6 * unit, 10 * unit]);"));
  assert.ok(mobileIntroFlow.includes("ctx.lineWidth = item.active ? 1.5 * unit : 1.15 * unit;"));
  assert.ok(mobileIntroFlow.includes("ctx.lineWidth = item.active ? 2.05 * unit : 1.35 * unit;"));
  assert.ok(mobileIntroFlow.includes("ctx.globalAlpha *= item.active ? 0.78 : 0.42;"));
  assert.ok(mobileIntroFlow.includes("ctx.setLineDash([5 * unit, 16 * unit]);"));
  assert.ok(mobileStory.includes("ctx.lineDashOffset = -introFlowMotion * 72 * unit;"));
  assert.ok(mobileStory.includes("ctx.lineDashOffset = -introFlowMotion * 118 * unit;"));
  assert.ok(mobileStory.includes("drawMobileIntroFlow(rect, item, index < 3 ? 1 : -1, flowAmount, index);"));
  assert.equal(mobileIntroMaterial.includes("drawMobileIntroRule(rect, item"), false);
  assert.ok(mobileStory.includes("const startX = introHeroX - measure(\"lsy\", heroSize, titleFont, 500) / 2;"));
  assert.ok(mobileStory.includes("const startY = introHeroY;"));
  assert.ok(mobileStory.includes("const titleXTravel = phase(amount, 0.02, 0.48);"));
  assert.ok(mobileStory.includes("const titleYTravel = phase(amount, 0.24, 1);"));
  assert.ok(mobileStory.includes("const titleSizeTravel = phase(amount, 0, 0.58);"));
  assert.ok(mobileStory.includes("const size = lerp(heroSize, smallSize * 1.08, titleSizeTravel);"));
  assert.ok(mobileStory.includes("const x = lerp(startX, endX, titleXTravel);"));
  assert.ok(mobileStory.includes("const y = lerp(startY, endY, titleYTravel);"));
  assert.ok(mobileStory.includes("const titleMorph = phase(progress, 0.14, 0.36);"));
  assert.ok(mobileChapterTitle.includes("const currentLabelAlpha = 1 - phase(handoff, 0.16, 0.5);"));
  assert.ok(mobileChapterTitle.includes("const nextLabelAlpha = phase(handoff, 0.24, 0.58);"));
  assert.ok(mobileChapterTitle.includes("withAlpha(ctx, currentLabelAlpha, () => {"));
  assert.ok(mobileChapterTitle.includes("withAlpha(ctx, nextLabelAlpha, () => {"));
  assert.equal(mobileChapterTitle.includes("const currentY = y - chapterSize * handoff;"), false);
  assert.equal(mobileChapterTitle.includes("const nextY = y + chapterSize * (1 - handoff);"), false);
  assert.equal(mobileChapterTitle.includes("const currentX = labelX - wipeW;"), false);
  assert.equal(mobileChapterTitle.includes("const nextX = labelX + Math.max(labelW, nextLabelW) - wipeW;"), false);
  assert.equal(mobileChapterTitle.includes("clipRect({ x: labelX + wipeW"), false);
  assert.ok(mobileStory.includes("const materialMorph = phase(amount, 0.16, 0.52);"));
  assert.ok(mobileStory.includes("const flowAmount = 1 - phase(materialMorph, 0.18, 0.62);"));
  assert.ok(mobileStory.includes("const detailAmount = phase(materialMorph, 0.42, 0.88);"));
  assert.ok(mobileStory.includes("const numberAlpha = phase(materialMorph, 0.18, 0.52);"));
  assert.ok(mobileStory.includes("const ruleW = lerp(60 * unit, Math.min(rect.w * 0.34, 70 * unit), materialMorph);"));
  assert.ok(mobileStory.includes("const ruleDotGap = 10 * unit;"));
  assert.ok(mobileStory.includes("const ruleStroke = item.active ? palette.aiAccent : palette.muted;"));
  assert.ok(mobileIntroMaterial.includes("const numberW = lerp(0, mobileInputNumberW, numberAlpha);"));
  assert.ok(mobileIntroMaterial.includes("mobileInputTitleMinSize"));
  assert.ok(mobileIntroMaterial.includes("wrapText(item.body, mobileInputBodyWidth"));
  assert.ok(mobileStory.includes("ctx.moveTo(rect.x + pad, ruleY);"));
  assert.ok(mobileStory.includes("ctx.lineTo(rect.x + pad + ruleW, ruleY);"));
  assert.ok(mobileStory.includes("ctx.arc(rect.x + pad + ruleW + ruleDotGap, ruleY, ruleDotRadius, 0, Math.PI * 2);"));
  assert.equal(mobileIntroMaterial.includes("if (item.active) {\n          ctx.beginPath();\n          ctx.arc(rect.x + pad + ruleW + ruleDotGap"), false);
  assert.ok(mobileStory.includes("withAlpha(ctx, 1, () => {"));
  assert.ok(mobileStory.includes("if (flowAmount > 0.01) {"));
  assert.ok(mobileStory.includes("drawMobileIntroFlow(rect, item, index < 3 ? 1 : -1, flowAmount, index);"));
  assert.equal([...mobileIntroMaterial.matchAll(/textFit\(item\.tag/g)].length, 1);
  assert.equal(mobileStory.includes("const introHeroY = height * 0.43;"), false);
  assert.equal(mobileStory.includes("const introSlotTop = safe.y + 82 * unit;"), false);
  assert.equal(mobileStory.includes("const introLabelAmount ="), false);
  assert.equal(mobileStory.includes("const cardAmount ="), false);
  assert.equal(mobileStory.includes("const materialMorph = phase(amount, 0.16, 0.84);"), false);
  assert.equal(mobileStory.includes("const detailAmount = phase(materialMorph, 0.52, 0.9);"), false);
  assert.equal(mobileStory.includes("startY + 56 * unit"), false);
  assert.equal(mobileStory.includes("startY - 56 * unit"), false);
  assert.equal(mobileStory.includes("rect.y + rect.h + 12 * unit"), false);
  assert.equal(mobileStory.includes("rect.y - 20 * unit"), false);
  assert.equal(mobileStory.includes("rect.y + rect.h + introFlowGap"), false);
  assert.equal(mobileStory.includes("rect.y - introFlowGap"), false);
  assert.equal(mobileIntroFlow.includes("const outerX ="), false);
  assert.equal(mobileIntroFlow.includes("const targetPullY ="), false);
  assert.equal(mobileIntroFlow.includes("const centerControlX ="), false);
  assert.equal(mobileIntroMaterial.includes("42 * unit"), false);
  assert.equal(mobileIntroMaterial.includes("wrapText(item.body, rect.w - pad * 2"), false);
  assert.equal(mobileStory.includes("const x = lerp(startX, endX, amount);"), false);
  assert.equal(mobileStory.includes("const y = lerp(startY, endY, amount);"), false);
});

test("mobile input renderer begins from the intro material end state", () => {
  assert.ok(mobileEditorialInput.includes("const ruleW = lerp(Math.min(rect.w * 0.34, 70 * unit), 56 * unit, toMethod);"));
  assert.ok(mobileEditorialInput.includes("const ruleColor = item.active ? palette.aiAccent : palette.muted;"));
  assert.ok(mobileEditorialInput.includes("ctx.strokeStyle = ruleColor;"));
  assert.ok(mobileEditorialInput.includes("ctx.fillStyle = ruleColor;"));
  assert.ok(mobileEditorialInput.includes("ctx.lineTo(rect.x + pad + ruleW, rect.y + 8 * unit);"));
  assert.ok(mobileEditorialInput.includes("ctx.arc(rect.x + pad + ruleW + 10 * unit, rect.y + 8 * unit, 3.8 * unit, 0, Math.PI * 2);"));
  assert.ok(mobileEditorialInput.includes("const titleX = rect.x + pad + mobileInputNumberW;"));
  assert.ok(mobileEditorialInput.includes("const titleMaxWidth = Math.max(1, maxWidth - mobileInputNumberW);"));
  assert.ok(mobileEditorialInput.includes("const titleMinSize = mobileInputTitleMinSize;"));
  assert.ok(mobileEditorialInput.includes("lerp(bodySize * 0.72, bodySize * 0.46, toMethod)"));
  assert.ok(mobileEditorialInput.includes("const metaAlpha = 1 - phase(toMethod, 0.18, 0.64);"));
  assert.equal(mobileEditorialInput.includes("drawMobileRule(rect.x + pad, rect.y + 8 * unit, ruleW, item.active, item.active);"), false);
  assert.equal(mobileEditorialInput.includes("if (item.active) {\n        ctx.save();\n        ctx.fillStyle = palette.aiAccent;"), false);
  assert.ok(mobileEditorialInput.includes("text(indexText, rect.x + pad, rect.y + 34 * unit"));
  assert.ok(mobileEditorialInput.includes("rect.y + 35 * unit"));
  assert.ok(mobileEditorialInput.includes("\"'JetBrains Mono', monospace\","));
  assert.equal(mobileEditorialInput.includes("lerp(34 * unit, 56 * unit, toMethod)"), false);
  assert.equal(mobileEditorialInput.includes("rect.x + pad + 42 * unit"), false);
  assert.equal(mobileEditorialInput.includes("rect.x + pad + 46 * unit"), false);
  assert.equal(mobileEditorialInput.includes("\"'Fraunces', 'Noto Serif SC', serif\""), false);
});

test("mobile input to classify rewrites the same moving groups instead of crossfading scenes", () => {
  assert.ok(mobileStory.includes("const mobileClassifyMaterialSlots = STORY_MATERIALS.map((item, index) => {"));
  assert.ok(mobileStory.includes("const pairIndexes = STORY_MATERIALS.map((candidate, candidateIndex) => (candidate.group === item.group ? candidateIndex : -1)).filter((candidateIndex) => candidateIndex >= 0);"));
  assert.ok(mobileStory.includes("const inputToClassify = clamp((progress - 0.36) / 0.2);"));
  assert.ok(mobileStory.includes("const groupPairs = STORY_TRACKS.map((_, group) =>"));
  assert.ok(mobileInputClassifyScene.includes("STORY_MATERIALS.map((item, index) => {"));
  assert.equal(mobileInputClassifyScene.includes("STORY_MATERIALS.forEach((item, index) => {\n      if (item.group !== group) return null;"), false);
  assert.ok(mobileStory.includes("const drawMobileClassifyMorphGroup = ("));
  assert.ok(mobileClassifyMorphGroup.includes("const pairTravel = phase(amount, 0.02, 0.56);"));
  assert.ok(mobileClassifyMorphGroup.includes("const pairFusion = phase(amount, 0.28, 0.66);"));
  assert.ok(mobileClassifyMorphGroup.includes("const titleExtract = phase(amount, 0.44, 0.82);"));
  assert.ok(mobileClassifyMorphGroup.includes("const noteRewrite = phase(amount, 0.76, 1);"));
  assert.ok(mobileClassifyMorphGroup.includes("const ruleBridgeAmount = fade(amount, 0.04, 0.24, 0.46, 0.68);"));
  assert.ok(mobileClassifyMorphGroup.includes("const groupRuleAmount = phase(amount, 0.2, 0.64);"));
  assert.ok(mobileClassifyMorphGroup.includes("const sourceIdentityAmount = 1 - phase(amount, 0.58, 0.86);"));
  assert.equal(mobileClassifyMorphGroup.includes("titleIdentityAmount"), false);
  assert.equal(mobileClassifyMorphGroup.includes("groupHeaderReveal"), false);
  assert.ok(mobileClassifyMorphGroup.includes("const travelRect = moveRect(pair.sourceRect, pair.targetRect, pairTravel);"));
  assert.ok(mobileClassifyMorphGroup.includes("const sourceRect = {"));
  assert.ok(mobileClassifyMorphGroup.includes("...travelRect,"));
  assert.ok(mobileClassifyMorphGroup.includes("w: lerp(pair.sourceRect.w, pair.targetRect.w, pairFusion),"));
  assert.ok(mobileClassifyMorphGroup.includes("h: lerp(pair.sourceRect.h, pair.targetRect.h, pairFusion),"));
  assert.ok(mobileClassifyMorphGroup.includes("const pairPad = lerp(10 * unit, 4 * unit, pairFusion);"));
  assert.ok(mobileClassifyMorphGroup.includes("const titleX = sourceRect.x + pairPad + mobileInputNumberW;"));
  assert.ok(mobileClassifyMorphGroup.includes("const titleMaxWidth = Math.max(1, sourceRect.w - pairPad * 2 - mobileInputNumberW);"));
  assert.ok(mobileClassifyMorphGroup.includes("const pairRuleW = lerp(Math.min(sourceRect.w * 0.34, 70 * unit), 56 * unit, pairFusion);"));
  assert.ok(mobileClassifyMorphGroup.includes("lerp(bodySize * 0.72, bodySize * 0.44, pairFusion)"));
  assert.ok(mobileClassifyMorphGroup.includes("mobileInputTitleMinSize"));
  assert.ok(mobileClassifyMorphGroup.includes("const gatheredPairs = pairs.map((pair) => {"));
  assert.ok(mobileClassifyMorphGroup.includes("const groupTextWidth = maxWidth;"));
  assert.ok(mobileClassifyMorphGroup.includes("const groupTitleX = lerp(gatheredPairs[0]?.titleX ?? rect.x + pad, rect.x + pad, titleExtract);"));
  assert.ok(mobileClassifyMorphGroup.includes("const groupTitleY = lerp(gatheredPairs[0]?.titleY ?? finalTitleY, finalTitleY, titleExtract);"));
  assert.ok(mobileClassifyMorphGroup.includes("const pairTitleFragments = gatheredPairs.map(({ pair, titleX, titleY, titleMaxWidth }, pairIndex) => {"));
  assert.ok(mobileClassifyMorphGroup.includes("const titleWords = track.title.split(\" / \");"));
  assert.ok(mobileClassifyMorphGroup.includes("const compactTitle = titleWords[pairIndex] ?? pair.item.title.split(\" \")[0] ?? pair.item.title;"));
  assert.ok(mobileClassifyMorphGroup.includes("const leftTitle = pairTitleFragments[0];"));
  assert.ok(mobileClassifyMorphGroup.includes("const rightTitle = pairTitleFragments[1];"));
  assert.ok(mobileClassifyMorphGroup.includes("const sourceTitleAmount = 1 - phase(titleExtract, 0.1, 0.5);"));
  assert.ok(mobileClassifyMorphGroup.includes("const compactTitleAmount = phase(titleExtract, 0.18, 0.62);"));
  assert.ok(mobileClassifyMorphGroup.includes("const slashAmount = phase(titleExtract, 0.38, 0.86);"));
  assert.ok(mobileClassifyMorphGroup.includes("text(\"/\", slashX, groupTitleY"));
  assert.ok(mobileClassifyMorphGroup.includes("if (sourceIdentityAmount > 0.001) {"));
  assert.ok(mobileClassifyMorphGroup.includes("const metaAmount = (1 - phase(pairFusion, 0.46, 0.9)) * sourceIdentityAmount;"));
  assert.ok(mobileClassifyMorphGroup.includes("const metaSize = smallSize * lerp(0.56, 0.54, pairFusion);"));
  assert.ok(mobileClassifyMorphGroup.includes("wrapText(pair.item.meta, mobileInputBodyWidth"));
  assert.ok(mobileClassifyMorphGroup.includes("ctx.globalAlpha *= (pair.item.active ? 0.78 : 0.62) * sourceIdentityAmount;"));
  assert.ok(mobileClassifyMorphGroup.includes("w: sourceRect.w - pairPad * 2"));
  assert.ok(mobileClassifyMorphGroup.includes("w: titleMaxWidth"));
  assert.ok(mobileClassifyMorphGroup.includes("leftClipW * compactTitleAmount"));
  assert.ok(mobileClassifyMorphGroup.includes("rightClipW * compactTitleAmount"));
  assert.ok(mobileClassifyMorphGroup.includes("clipRect({ x: groupTitleX, y: groupTitleY - bodySize"));
  assert.ok(mobileClassifyMorphGroup.includes("withAlpha(ctx, groupRuleAmount, () => {"));
  assert.ok(mobileClassifyMorphGroup.includes("drawRuleBridgePath(sourceRect, pairPad, pairRuleW, pair.item.active, pair.index);"));
  assert.ok(mobileClassifyMorphGroup.includes("clipRect({ x: titleX, y: titleY - bodySize, w: titleMaxWidth, h: bodySize * 1.5 }, () => {"));
  assert.equal(mobileClassifyMorphGroup.includes("clipRect({ x: titleX, y: titleY - bodySize, w: titleMaxWidth * identityAmount"), false);
  assert.equal(mobileClassifyMorphGroup.includes("clipRect({ x: rect.x + pad, y: rect.y + 18 * unit, w: rect.w * groupRewrite"), false);
  assert.equal(mobileClassifyMorphGroup.includes("textFit(track.title, groupTitleX, groupTitleY"), false);
  assert.ok(mobileStory.includes("const inputChapterHandoff = phase(inputToClassify, 0.66, 0.94);"));
  assert.ok(mobileInputClassifyScene.includes("const nextChapter = chapter === \"input\" ? \"classify\" : chapter === \"classify\" && classifyToWork > 0.08 ? \"work\" : chapter;"));
  assert.ok(mobileInputClassifyScene.includes("drawMobileClassifyMorphGroup(trackRect, track, index, inputToClassify, groupPairs[index]);"));
  assert.ok(mobileStory.includes("drawMobileChapterTitle(chapter, titleMorph, nextChapter, chapterHandoff);"));
  assert.ok(mobileInputClassifyScene.includes("if (progress < 0.36) {"));
  assert.equal(mobileStory.includes("const inputSceneHold = 1 - phase(toMethod, 0.12, 0.34);"), false);
  assert.equal(mobileInputClassifyScene.includes("if (toMethod < 0.01) {"), false);
  assert.equal(mobileStory.includes("const inputToClassify = phase(toMethod"), false);
  assert.equal(mobileStory.includes("const inputToClassify = clamp((progress - 0.42) / 0.2);"), false);
  assert.equal(mobileStory.includes("const inputToClassify = phase(progress, 0.42, 0.66);"), false);
  assert.equal(mobileStory.includes("const inputToClassify = phase(progress, 0.42, 0.66);"), false);
  assert.equal(mobileStory.includes("const classifySceneReveal = phase(toMethod, 0.34, 0.58);"), false);
  assert.equal(mobileStory.includes("const classifyTextReveal ="), false);
  assert.equal(mobileStory.includes("const inputMaterialAlpha ="), false);
  assert.equal(mobileInputClassifyScene.includes("withAlpha(ctx, inputMaterialAlpha"), false);
  assert.equal(mobileInputClassifyScene.includes("drawMobileClassifyTrack(trackRect, track, index, trackAmount"), false);
  assert.equal(mobileInputClassifyScene.includes("h: (rect.h + 24 * unit) * inputSceneHold"), false);
  assert.equal(mobileStory.includes("const chapter = inputToClassify < 0.72 ? \"input\""), false);
});

test("mobile classify to work expands making instead of swapping scenes", () => {
  assert.ok(mobileEditorialWork.includes("const workTitleSize = bodySize * lerp(0.62, 0.68, amount);"));
  assert.ok(mobileRule.includes("const ruleColor = active ? activeInk(true, aiSignal) : palette.muted;"));
  assert.ok(mobileRule.includes("ctx.strokeStyle = ruleColor;"));
  assert.ok(mobileRule.includes("ctx.fillStyle = ruleColor;"));
  assert.ok(mobileRule.includes("ctx.lineWidth = 1.35 * unit;"));
  assert.ok(mobileRule.includes("ctx.arc(x + w + 10 * unit, y, 3.6 * unit, 0, Math.PI * 2);"));
  assert.equal(mobileRule.includes("ctx.strokeStyle = active ? activeInk(true, aiSignal) : palette.line;"), false);
  assert.ok(mobileEditorialWork.includes("const workBodyY = Math.min(rect.y + 132 * unit, rect.y + rect.h - 16 * unit);"));
  assert.ok(mobileEditorialWork.includes("textReveal = amount,"));
  assert.ok(mobileEditorialWork.includes("const textAmount = showSourceText ? amount : textReveal;"));
  assert.ok(mobileEditorialWork.includes("const sourceTextAlpha = showSourceText ? 1 - phase(amount, 0.14, 0.32) : 0;"));
  assert.ok(mobileEditorialWork.includes("const workTextAlpha = showSourceText ? phase(amount, 0.24, 0.52) : phase(textAmount, 0.08, 0.42);"));
  assert.ok(mobileEditorialWork.includes("const headerSourceAlpha = showSourceText ? 1 - phase(amount, 0.16, 0.34) : 0;"));
  assert.ok(mobileEditorialWork.includes("const headerWorkAlpha = showSourceText ? phase(amount, 0.38, 0.58) : 0;"));
  assert.ok(mobileEditorialWork.includes("const handoffHeaderAlpha = showSourceText ? fade(amount, 0.12, 0.18, 0.62, 0.78) : 0;"));
  assert.ok(mobileEditorialWork.includes("const headerNumberAlpha = Math.max(headerSourceAlpha, headerWorkAlpha, handoffHeaderAlpha);"));
  assert.ok(mobileEditorialWork.includes("if (showSourceText && headerNumberAlpha > 0.001) {"));
  assert.ok(mobileEditorialWork.includes("withAlpha(ctx, headerNumberAlpha, () => {"));
  assert.ok(mobileEditorialWork.includes("withAlpha(ctx, headerSourceAlpha, () => {"));
  assert.ok(mobileEditorialWork.includes("withAlpha(ctx, headerWorkAlpha, () => {"));
  assert.ok(mobileEditorialWork.includes("withAlpha(ctx, sourceTextAlpha, () => {"));
  assert.ok(mobileEditorialWork.includes("withAlpha(ctx, workTextAlpha, () => {"));
  assert.ok(mobileEditorialWork.includes("if (!showSourceText) {"));
  assert.equal(mobileEditorialWork.includes("const sourceTextClip = showSourceText ? 1 - phase(amount, 0.34, 0.64) : 0;"), false);
  assert.equal(mobileEditorialWork.includes("const workTextClip = showSourceText ? phase(amount, 0.24, 0.58) : phase(amount, 0.08, 0.42);"), false);
  assert.equal(mobileEditorialWork.includes("const sourceTextAlpha = showSourceText ? 1 - phase(amount, 0.2, 0.42) : 0;"), false);
  assert.equal(mobileEditorialWork.includes("const workTextAlpha = showSourceText ? phase(amount, 0.48, 0.7) : phase(amount, 0.08, 0.42);"), false);
  assert.equal(mobileEditorialWork.includes("const headerSourceAlpha = showSourceText ? 1 - phase(amount, 0.24, 0.46) : 0;"), false);
  assert.equal(mobileEditorialWork.includes("const headerWorkAlpha = showSourceText ? phase(amount, 0.32, 0.56) : 0;"), false);
  assert.ok(mobileEditorialWork.includes("textFit(row.title, rect.x + pad, rect.y + 79 * unit, workTitleSize"));
  assert.ok(mobileEditorialWork.includes("clipRect({ x: rect.x, y: workBodyY - smallSize"));
  assert.equal(mobileEditorialWork.includes("bodySize * 0.72"), false);
  assert.ok(mobileStory.includes("const drawMobileClassifyToWorkMorph = (amount: number) => {"));
  assert.ok(mobileClassifyWorkMorph.includes("const classifyHandoff = phase(amount, 0.08, 0.38);"));
  assert.ok(mobileClassifyWorkMorph.includes("const sideFold = classifyHandoff;"));
  assert.ok(mobileClassifyWorkMorph.includes("const sideFade = classifyHandoff;"));
  assert.ok(mobileClassifyWorkMorph.includes("const sideMove = classifyHandoff;"));
  assert.ok(mobileClassifyWorkMorph.includes("const centerRewrite = classifyHandoff;"));
  assert.ok(mobileClassifyWorkMorph.includes("const splitAmount = phase(amount, 0.2, 0.78);"));
  assert.equal(mobileClassifyWorkMorph.includes("const sideFade = phase(amount, 0.04, 0.24);"), false);
  assert.equal(mobileClassifyWorkMorph.includes("const sideMove = phase(amount, 0.24, 0.58);"), false);
  assert.equal(mobileClassifyWorkMorph.includes("const centerRewrite = phase(amount, 0.08, 0.78);"), false);
  assert.ok(mobileClassifyWorkMorph.includes("const centerRect = moveRect(centerClassifyRect, workRects[1], amount);"));
  assert.ok(mobileClassifyWorkMorph.includes("drawMobileEditorialWork(centerRect, workRows[1], 1, centerRewrite, true, 1);"));
  assert.ok(mobileClassifyWorkMorph.includes("if (index === 1) return;"));
  assert.ok(mobileClassifyWorkMorph.includes("const trackRect = moveRect(mobileTrackRects[index], sink, sideMove);"));
  assert.ok(mobileClassifyWorkMorph.includes("withAlpha(ctx, 1 - sideFade, () => {"));
  assert.ok(mobileClassifyWorkMorph.includes("drawMobileClassifyMorphGroup(trackRect, track, index, 1, groupPairs[index]);"));
  assert.ok(mobileClassifyWorkMorph.includes("const sourceRect = centerRect;"));
  assert.ok(mobileClassifyWorkMorph.includes("const rowRect = moveRect(sourceRect, workRects[index], rowSplit);"));
  assert.ok(mobileClassifyWorkMorph.includes("const rowTextReveal = phase(rowSplit, 0.46, 0.84);"));
  assert.ok(mobileClassifyWorkMorph.includes("drawMobileEditorialWork(rowRect, row, index, rowSplit, false, rowSplit, rowTextReveal);"));
  assert.equal(mobileClassifyWorkMorph.includes("drawMobileEditorialWork(rowRect, row, index, rowSplit, false, rowSplit);"), false);
  assert.ok(mobileStory.includes("const makingFocus = clamp((progress - 0.58) / 0.34);"));
  assert.ok(mobileStory.includes("const classifyToWork = makingFocus;"));
  assert.ok(mobileStory.includes("drawMobileClassifyToWorkMorph(classifyToWork);"));
  assert.ok(mobileStory.includes("const workChapterHandoff = phase(classifyToWork, 0.18, 0.58);"));
  assert.ok(mobileStory.includes("chapter === \"classify\" && classifyToWork > 0.08 ? \"work\""));
  assert.equal(mobileStory.includes("const workSceneActive = makingFocus > 0.18"), false);
  assert.equal(mobileStory.includes("} else if (makingFocus < 0.18) {"), false);
});

test("mobile work to today bridge compresses the same rows without drawing duplicates", () => {
  assert.ok(mobileStory.includes("const buildBridgeActive = buildBridge > 0.001;"));
  assert.ok(mobileStory.includes("} else if (!buildBridgeActive) {"));
  assert.ok(mobileStory.includes("if (buildBridge > 0.001) {"));
  assert.equal(mobileStory.includes("} else if (buildBridge < 0.02) {"), false);
  assert.ok(mobileBuildIndexRow.includes("const ruleY = rect.y + lerp(8 * unit, 1 * unit, amount);"));
  assert.ok(mobileBuildIndexRow.includes("const compactRuleAlpha = 1 - phase(amount, 0.72, 0.98);"));
  assert.ok(mobileBuildIndexRow.includes("const fullDetailsAlpha = 1 - phase(amount, 0.24, 0.52);"));
  assert.ok(mobileBuildIndexRow.includes("const compactTitleAlpha = phase(amount, 0.38, 0.66);"));
  assert.ok(mobileBuildIndexRow.includes("withAlpha(ctx, compactRuleAlpha, () => {"));
  assert.ok(mobileBuildIndexRow.includes("drawMobileRule(rect.x + pad, ruleY, ruleW, row.active, row.active);"));
  assert.ok(mobileBuildIndexRow.includes("withAlpha(ctx, fullDetailsAlpha, () => {"));
  assert.ok(mobileBuildIndexRow.includes("textFit(row.title, rect.x + pad, rect.y + 79 * unit"));
  assert.ok(mobileBuildIndexRow.includes("withAlpha(ctx, compactTitleAlpha, () => {"));
  assert.equal(mobileBuildIndexRow.includes("if (amount < 0.48) {"), false);
});

test("mobile today layout separates hero, build index, paired panels, and footer", () => {
  assert.ok(mobileStory.includes("const todayStatusTop = todayRect.y + todayRect.h - 52 * unit;"));
  assert.ok(mobileStory.includes("const todayHeroNameY = todayTop + 90 * unit;"));
  assert.ok(mobileStory.includes("const todayHeroRoleY = todayHeroNameY + 52 * unit;"));
  assert.ok(mobileStory.includes("const todayHeroSummaryY = todayHeroRoleY + 32 * unit;"));
  assert.ok(mobileStory.includes("const todayHeroSummarySize = smallSize * 0.54;"));
  assert.ok(mobileStory.includes("const todayBuildTop = Math.min(todayTop + 242 * unit, todayStatusTop - 220 * unit);"));
  assert.ok(mobileStory.includes("const todayBuildRowsTop = todayBuildTop + 39 * unit;"));
  assert.ok(mobileStory.includes("const todayBuildRowGap = 22 * unit;"));
  assert.ok(mobileStory.includes("const todayBuildH = todayBuildRowsTop - todayBuildTop + todayBuildRowGap * (workRows.length - 1) + 16 * unit;"));
  assert.ok(mobileStory.includes("const todayPanelTop = todayBuildTop + todayBuildH + 35 * unit;"));
  assert.ok(mobileStory.includes("const todayPanelGap = 14 * unit;"));
  assert.ok(mobileStory.includes("const todayPanelW = (todayRect.w - todayPad * 2 - todayPanelGap) / 2;"));
  assert.ok(mobileStory.includes("x: todayRect.x + todayPad + index * (todayPanelW + todayPanelGap),"));
  assert.ok(mobileStory.includes("y: todayBuildRowsTop + index * todayBuildRowGap,"));
  assert.ok(mobileStory.includes("textFit(\"full-stack & AI engineer\", rect.x + todayPad, todayHeroRoleY, smallSize * 0.62"));
  assert.ok(mobileStory.includes("wrapText(\"working with AI, writing, and the world\", rect.w - todayPad * 2, todayHeroSummarySize"));
  assert.ok(mobileStory.includes("textFit(STORY_STATUS, rect.x + todayPad, todayStatusTop + 24 * unit, smallSize * 0.56"));
  assert.ok(mobileTodayPanel.includes("const panelReveal = phase(amount, 0.22 + index * 0.06, 0.56 + index * 0.06);"));
  assert.ok(mobileTodayPanel.includes("drawMobileRule(rect.x + pad, rect.y + 5 * unit, rect.w * 0.34, index === 0);"));
  assert.ok(mobileTodayPanel.includes("const panelTitleSize = fitSize(title, maxWidth, smallSize * 0.54, smallSize * 0.34"));
  assert.ok(mobileTodayPanel.includes("const compactTitleLines = title.includes(\" · \") && measure(title, panelTitleSize, \"'JetBrains Mono', monospace\", 700) > maxWidth"));
  assert.ok(mobileTodayPanel.includes("? title.split(\" · \")"));
  assert.ok(mobileTodayPanel.includes(": wrapText(title, maxWidth, panelTitleSize, \"'JetBrains Mono', monospace\", 700, 3);"));
  assert.ok(mobileTodayPanel.includes("const titleLines = compactTitleLines.slice(0, 3);"));
  assert.ok(mobileTodayPanel.includes("const panelTitleY = rect.y + 49 * unit;"));
  assert.ok(mobileTodayPanel.includes("const panelLineGap = titleLines.length > 2 ? 13 * unit : 16 * unit;"));
  assert.ok(mobileTodayPanel.includes("const [label, title] = panel;"));
  assert.equal(mobileTodayPanel.includes("wrapText(body"), false);
  assert.equal(mobileTodayPanel.includes("rect.y + rect.h - 9 * unit"), false);
  assert.equal(mobileStory.includes("const todayBuildTop = todayTop + 228 * unit;"), false);
  assert.equal(mobileStory.includes("y: todayBuildTop + 24 * unit + index * 18 * unit,"), false);
});
