/* eslint-disable */
// This file is auto-generated by scripts/generate-function-wrappers.mjs.
// Do not edit it by hand.
import { dispatchFunctionRequest } from "../../src/server/function-dispatch.js";
import { GET, OPTIONS as SHARED_OPTIONS } from "../../src/server/api/git-projects.js";

const handlers = {
  GET: GET,
  OPTIONS: SHARED_OPTIONS,
};

export function onRequestGet(context: { request: Request }) {
  return dispatchFunctionRequest("edgeone", context.request, handlers);
}

export function onRequestOptions(context: { request: Request }) {
  return dispatchFunctionRequest("edgeone", context.request, handlers);
}
