/* eslint-disable */
// This file is auto-generated by scripts/generate-function-wrappers.mjs.
// Do not edit it by hand.
import { dispatchFunctionRequest } from "../../src/server/function-dispatch.js";
import { GET } from "../../src/server/api/weread.js";

const handlers = {
  GET: GET,
};

export function onRequestGet(context: { request: Request }) {
  return dispatchFunctionRequest("cloudflare", context.request, handlers);
}

export function onRequestOptions(context: { request: Request }) {
  return dispatchFunctionRequest("cloudflare", context.request, handlers);
}
