/* eslint-disable */
// This file is auto-generated by scripts/generate-function-wrappers.mjs.
// Do not edit it by hand.
import { handleVercelNodeRequest } from "../src/server/vercel-node.js";
import { GET as handleGet, OPTIONS as handleOptions } from "../src/server/api/git-projects.js";

const handlers = {
  GET: handleGet,
  OPTIONS: handleOptions,
};

export default function handler(req: unknown, res: unknown) {
  return handleVercelNodeRequest(
    req as Parameters<typeof handleVercelNodeRequest>[0],
    res as Parameters<typeof handleVercelNodeRequest>[1],
    handlers,
  );
}
